import test from 'node:test'; import assert from 'node:assert/strict';
import { saveAccounts, loadAccounts, ACCOUNTS_KEY } from '../../accountPersistence.mjs';
function store(seed={}){const m=new Map(Object.entries(seed));return{m,getItemAsync:async k=>m.get(k)??null,setItemAsync:async(k,v)=>{m.set(k,v)},deleteItemAsync:async k=>m.delete(k)}}
test('session survives a cold restart and time passage without sharing token in metadata',async()=>{const s=store(),a={id:'a',apiKey:'jwt.forever.sig',name:'Z'};await saveAccounts(s,[a],'a');assert.ok(!s.m.get(ACCOUNTS_KEY).includes('jwt.forever.sig'));Date.now=()=>9e15;assert.deepEqual(await loadAccounts(s),[a])});
test('legacy combined account storage migrates atomically',async()=>{const a={id:'old',apiKey:'legacy.jwt',name:'Z'},s=store({botmanager_accounts:JSON.stringify([a]),botmanager_active_account_id:'old'});assert.deepEqual(await loadAccounts(s),[a]);assert.match(s.m.get(ACCOUNTS_KEY),/"version":3/)});
test('storage failure is surfaced instead of leaving a memory-only login',async()=>{const s=store();s.setItemAsync=async()=>{throw Error('secure_store_write_failed')};await assert.rejects(()=>saveAccounts(s,[{id:'a',apiKey:'jwt'}],'a'),/secure_store_write_failed/)});
test('partial write keeps the previous committed session readable',async()=>{const s=store(),old={id:'a',apiKey:'old.jwt'};await saveAccounts(s,[old],'a');let writes=0;const real=s.setItemAsync;s.setItemAsync=async(k,v)=>{if(++writes===2)throw Error('power_loss');return real(k,v)};await assert.rejects(()=>saveAccounts(s,[{id:'a',apiKey:'new.jwt'}],'a'),/power_loss/);assert.deepEqual(await loadAccounts(s),[old])});
test('corrupt metadata is explicit and never treated as signed out',async()=>{const s=store({botmanager_accounts_v2:'{broken'});await assert.rejects(()=>loadAccounts(s),/account_metadata_corrupt/)});
test('missing token for committed metadata drops only that unusable account',async()=>{const s=store({botmanager_accounts_v2:JSON.stringify({version:3,revision:'r',accounts:[{id:'lost'},{id:'ok'}]}),botmanager_account_token_r_ok:'valid.jwt'});assert.deepEqual(await loadAccounts(s),[{id:'ok',apiKey:'valid.jwt'}])});
