// worker/src/lib/botWebhookDelivery.ts
//
// PHASE 16 — Bot Webhook System.
//
// Everything a real webhook-delivery system needs, for the per-bot
// webhook configured in `bot_webhooks` (see schema.sql's PHASE 16 block
// for why this is a separate table from the dev-platform `webhooks`):
//   - URL validation, including a real (best-effort) SSRF guard
//   - HMAC-SHA256 signing, via the same derive-key pattern
//     lib/relaySigning.ts already uses for the relay layer, so a bot's
//     webhook secret is never used to sign anything outside this purpose
//   - Stable per-event IDs + a timestamp in every signed payload, so a
//     receiver can enforce freshness/replay-rejection the same way
//     relaySigning.ts's own replay guard does for inbound relay calls
//   - Real delivery attempts (genuine `fetch()`, never a fabricated
//     "delivered"), with retry/backoff for the async event stream
//   - Every attempt recorded to `bot_webhook_deliveries`: attempt number,
//     status, HTTP response code, latency
//
// What this file deliberately does NOT do: it never sends `bots.token_hash`
// or a raw bot token in any payload or header. The only credential that
// ever leaves the Worker on this path is the per-webhook HMAC signature,
// derived from `bot_webhooks.secret_hash`'s raw counterpart — a value
// distinct from the bot's own auth token, generated by
// `generateWebhookSecret()` (lib/keys.ts), exactly like the dev-platform
// webhook secret.

import { uid, hashToken, generateWebhookSecret } from './keys';
import { hmacSign, hmacVerify } from './relaySigning';

const SIGN_PURPOSE = 'bot-webhook';
const DELIVERY_TIMEOUT_MS = 8000;

// Bounded retry schedule for the async, no-reply-needed event stream
// (`bot.message.received` / `bot.message.sent` notifications). Capped at
// 5 total attempts with capped exponential backoff — long enough to ride
// out a receiver's brief blip, short enough to fit inside a Worker's
// `waitUntil` execution budget.
const RETRY_BACKOFF_MS = [1_000, 3_000, 7_000, 15_000];
const MAX_ATTEMPTS = RETRY_BACKOFF_MS.length + 1; // 5

export interface BotWebhookRow {
  id: string;
  bot_id: string;
  url: string;
  secret_hash: string;
  secret_prefix: string;
  enabled: number;
  last_delivery_at: number | null;
  last_delivery_code: number | null;
  last_delivery_status: string | null;
  created_at: number;
  updated_at: number;
}

// ── URL validation (shape + SSRF guard) ─────────────────────────────────────
//
// Stricter than the legacy `isValidWebhookUrl` in routes/bots.ts on
// purpose — that one guards the old free-text `webhook_url` field used
// for the synchronous bot-logic callback (Phase 11, http(s) allowed, any
// host). This is the NEW dedicated webhook config the spec asks to
// "properly" build, so it enforces the spec's own bullets directly:
// "Validate webhook URL" (https-only) and "Protect the webhook system
// against SSRF where applicable".
//
// Honest limitation: a Cloudflare Worker has no raw DNS-resolution API to
// call before `fetch()`, so this can only reject IP-literal hosts in
// private/loopback/link-local/reserved ranges and well-known
// local/metadata hostnames — it cannot catch a hostname that resolves to
// a private IP only at request time (DNS rebinding). That gap is real and
// stated here rather than glossed over; closing it needs a Worker with an
// egress/DNS-resolution binding, which this project does not have.
export type WebhookUrlError = 'missing' | 'invalid_url' | 'https_required' | 'blocked_host';

export function checkWebhookUrl(raw: unknown): { ok: true; url: string } | { ok: false; error: WebhookUrlError } {
  if (typeof raw !== 'string' || !raw.trim()) return { ok: false, error: 'missing' };
  let parsed: URL;
  try {
    parsed = new URL(raw.trim());
  } catch {
    return { ok: false, error: 'invalid_url' };
  }
  if (parsed.protocol !== 'https:') return { ok: false, error: 'https_required' };
  if (isBlockedHost(parsed.hostname)) return { ok: false, error: 'blocked_host' };
  return { ok: true, url: parsed.toString() };
}

function isBlockedHost(hostname: string): boolean {
  const host = hostname.toLowerCase().replace(/^\[|\]$/g, ''); // strip IPv6 brackets
  if (host === 'localhost' || host.endsWith('.localhost') || host.endsWith('.local')) return true;
  if (host === '0.0.0.0') return true;
  // Cloud metadata endpoint — a classic SSRF target regardless of cloud.
  if (host === '169.254.169.254' || host === 'metadata.google.internal') return true;

  const ipv4 = host.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);
  if (ipv4) {
    const [a, b] = [Number(ipv4[1]), Number(ipv4[2])];
    if (a === 127) return true;                                  // loopback
    if (a === 10) return true;                                   // 10.0.0.0/8
    if (a === 172 && b >= 16 && b <= 31) return true;             // 172.16.0.0/12
    if (a === 192 && b === 168) return true;                      // 192.168.0.0/16
    if (a === 169 && b === 254) return true;                      // link-local
    if (a === 0) return true;                                     // "this network"
    return false;
  }
  // IPv6 loopback / unique-local / link-local literals.
  if (host === '::1') return true;
  if (/^fe80:/i.test(host)) return true;
  if (/^f[cd][0-9a-f]{2}:/i.test(host)) return true;
  return false;
}

// ── Signing ──────────────────────────────────────────────────────────────────
// Reuses lib/relaySigning.ts's `hmacSign`/`hmacVerify` (purpose-scoped
// HMAC-SHA256 key derivation) rather than a second hand-rolled signer —
// same primitive, same derive-then-sign shape, different purpose string
// so a bot-webhook secret's signature can never be replayed as a valid
// relay signature or vice versa.
export async function signBotWebhookPayload(secret: string, canonicalBody: string): Promise<string> {
  return hmacSign(canonicalBody, secret, SIGN_PURPOSE);
}

export async function verifyBotWebhookSignature(secret: string, canonicalBody: string, signature: string): Promise<boolean> {
  return hmacVerify(canonicalBody, signature, secret, SIGN_PURPOSE);
}

export interface BotWebhookEventPayload {
  event_id: string;
  event: string;
  bot_id: string;
  timestamp: number;
  data: Record<string, unknown>;
}

// Every signed body carries its own `event_id` + `timestamp` inline (not
// just in headers) — Phase 16 spec: "Add a timestamp + event_id to every
// signed payload so the same replay-protection pattern from Phase 4
// applies here too." A receiver that verifies the signature over the raw
// body AND rejects a stale `timestamp` / already-seen `event_id` gets the
// exact same freshness + replay guard `lib/relaySigning.ts`'s
// `verifyRelaySignature` implements for inbound relay calls — this is the
// sending half of that same pattern.
export function buildEventPayload(botId: string, eventType: string, data: Record<string, unknown>): BotWebhookEventPayload {
  return { event_id: uid(), event: eventType, bot_id: botId, timestamp: Date.now(), data };
}

// ── Delivery (single real attempt) ──────────────────────────────────────────
export interface DeliveryAttemptResult {
  ok: boolean;
  code: number | null;
  latencyMs: number;
}

async function attemptDelivery(url: string, secret: string, payload: BotWebhookEventPayload): Promise<DeliveryAttemptResult> {
  const body = JSON.stringify(payload);
  const signature = await signBotWebhookPayload(secret, body);
  const started = Date.now();
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), DELIVERY_TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        // Never `Authorization` / the bot's own token — a separate,
        // purpose-built signature header instead (spec: "Use a separate
        // webhook secret/signature mechanism", "Never send the bot token
        // inside webhook payloads").
        'X-Bot-Signature': signature,
        'X-Bot-Event-Id': payload.event_id,
        'X-Bot-Event': payload.event,
        'X-Bot-Timestamp': String(payload.timestamp),
      },
      body,
      signal: controller.signal,
    });
    return { ok: res.ok, code: res.status, latencyMs: Date.now() - started };
  } catch {
    // Network error, timeout, DNS failure, refused connection — a real,
    // un-fabricated failure. `code: null` means "no HTTP response was
    // ever received", distinct from a real non-2xx status.
    return { ok: false, code: null, latencyMs: Date.now() - started };
  } finally {
    clearTimeout(timer);
  }
}

async function recordAttempt(
  db: D1Database,
  webhookId: string,
  eventId: string,
  eventType: string,
  attempt: number,
  status: 'delivered' | 'failed' | 'exhausted',
  code: number | null,
  latencyMs: number,
): Promise<void> {
  const now = Date.now();
  await db.prepare(
    `INSERT INTO bot_webhook_deliveries (id, webhook_id, event_id, event_type, attempt, status, response_code, latency_ms, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
  ).bind(uid(), webhookId, eventId, eventType, attempt, status, code, latencyMs, now).run();
  await db.prepare(
    'UPDATE bot_webhooks SET last_delivery_at = ?, last_delivery_code = ?, last_delivery_status = ?, updated_at = ? WHERE id = ?'
  ).bind(now, code, status, now, webhookId).run();
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ── One-shot signed delivery, no retry ──────────────────────────────────────
// Used for the synchronous "process bot logic" callback
// (botMessagePipeline.ts's `processCommandOrLogicOrWebhook` /
// `deliverAndRecordOutbound`), which is awaited inside a live inbound
// request and needs the reply body back immediately — retrying that with
// backoff would mean holding the sender's HTTP request open for up to
// ~26s per Phase 16's retry schedule, which is not an acceptable
// trade-off for "give me a reply now". Still fully signed and still
// recorded to `bot_webhook_deliveries` (attempt 1) for a complete
// delivery history, same as every other event.
export async function deliverBotWebhookOnce(
  db: D1Database,
  webhook: BotWebhookRow,
  secret: string,
  eventType: string,
  data: Record<string, unknown>,
): Promise<{ result: DeliveryAttemptResult; eventId: string; responseBody: any }> {
  const payload = buildEventPayload(webhook.bot_id, eventType, data);
  const body = JSON.stringify(payload);
  const signature = await signBotWebhookPayload(secret, body);
  const started = Date.now();
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), DELIVERY_TIMEOUT_MS);
  let result: DeliveryAttemptResult;
  let responseBody: any = null;
  try {
    const res = await fetch(webhook.url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Bot-Signature': signature,
        'X-Bot-Event-Id': payload.event_id,
        'X-Bot-Event': payload.event,
        'X-Bot-Timestamp': String(payload.timestamp),
      },
      body,
      signal: controller.signal,
    });
    result = { ok: res.ok, code: res.status, latencyMs: Date.now() - started };
    responseBody = await res.json().catch(() => null);
  } catch {
    result = { ok: false, code: null, latencyMs: Date.now() - started };
  } finally {
    clearTimeout(timer);
  }
  await recordAttempt(db, webhook.id, payload.event_id, eventType, 1, result.ok ? 'delivered' : 'failed', result.code, result.latencyMs);
  return { result, eventId: payload.event_id, responseBody };
}

// ── Retried async delivery (fire-and-forget event stream) ──────────────────
// For events nothing is waiting on a reply for (`bot.message.received`,
// `bot.message.sent`, `bot.webhook.test`). Intended to be handed to
// `c.executionCtx.waitUntil(...)` by the caller so the owner-facing
// request returns immediately while retries continue in the background —
// this function itself just does the real work: attempt, record, sleep,
// retry, up to `MAX_ATTEMPTS`, stopping the moment one attempt succeeds.
export async function deliverBotWebhookWithRetry(
  db: D1Database,
  webhook: BotWebhookRow,
  secret: string,
  eventType: string,
  data: Record<string, unknown>,
): Promise<void> {
  const payload = buildEventPayload(webhook.bot_id, eventType, data);
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    const result = await attemptDelivery(webhook.url, secret, payload);
    if (result.ok) {
      await recordAttempt(db, webhook.id, payload.event_id, eventType, attempt, 'delivered', result.code, result.latencyMs);
      return;
    }
    const isLastAttempt = attempt === MAX_ATTEMPTS;
    await recordAttempt(db, webhook.id, payload.event_id, eventType, attempt, isLastAttempt ? 'exhausted' : 'failed', result.code, result.latencyMs);
    if (isLastAttempt) return;
    await sleep(RETRY_BACKOFF_MS[attempt - 1]);
  }
}

// ── Secret generation / hashing (mirrors dev-platform webhook secrets) ─────
export { generateWebhookSecret, hashToken };

// ── Event-stream trigger helper ─────────────────────────────────────────────
// Shared by every real call site that fires a `bot.*` event (currently:
// routes/other.ts's inbound webhook handler, for `bot.message.received` /
// `bot.message.sent`). Looks up the bot's webhook once, does nothing at
// all if none is configured or it's disabled — no event is ever queued
// for a bot that hasn't set one up — otherwise kicks off the retried
// delivery. Callers hand the returned promise to
// `c.executionCtx.waitUntil(...)` so it delivers in the background instead
// of holding the inbound request open for retries.
export async function fireBotWebhookEvent(
  db: D1Database,
  botId: string,
  eventType: string,
  data: Record<string, unknown>,
): Promise<void> {
  const webhook = await db.prepare('SELECT * FROM bot_webhooks WHERE bot_id = ? AND enabled = 1').bind(botId).first<BotWebhookRow>();
  if (!webhook) return;
  await deliverBotWebhookWithRetry(db, webhook, webhook.secret_hash, eventType, data);
}
