import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { View, Text, FlatList, Pressable, StyleSheet, RefreshControl } from 'react-native';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { fetchRelayChannel, fetchRelayChannelMessages, pollRelayChannel } from '../../../../relayApi';
import { useTheme, type, space, radius } from '../../../../theme';
import { ErrorState } from '../../../../components/StateViews';

const dedupe = (rows) => [...new Map(rows.map((row)=>[row.id,row])).values()].sort((a,b)=>(a.createdAt-b.createdAt)||a.id.localeCompare(b.id));
export default function RelayChannelScreen(){
 const {channelId}=useLocalSearchParams(); const router=useRouter(); const {colors}=useTheme(); const styles=useMemo(()=>makeStyles(colors),[colors]); const list=useRef(null);
 const [channel,setChannel]=useState(null),[messages,setMessages]=useState([]),[older,setOlder]=useState(null),[hasMore,setHasMore]=useState(false),[pollCursor,setPollCursor]=useState(null),[phase,setPhase]=useState('loading'),[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async()=>{try{const [ch,page]=await Promise.all([fetchRelayChannel(channelId),fetchRelayChannelMessages(channelId)]);const rows=page.items??[];setChannel(ch);setMessages(rows);setOlder(page.nextCursor);setHasMore(page.hasMore);setPollCursor(rows.length?rows[rows.length-1].cursor:null);setPhase('ready')}catch{setPhase('error')}},[channelId]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(phase!=='ready')return;const timer=setInterval(async()=>{try{const page=await pollRelayChannel(channelId,pollCursor);if(page.items?.length)setMessages((old)=>dedupe([...old,...page.items]));if(page.nextCursor)setPollCursor(page.nextCursor)}catch{}},5000);return()=>clearInterval(timer)},[channelId,phase,pollCursor]);
 async function history(){if(!hasMore||!older)return;try{const page=await fetchRelayChannelMessages(channelId,older);setMessages((old)=>dedupe([...(page.items??[]),...old]));setOlder(page.nextCursor);setHasMore(page.hasMore)}catch{setPhase('error')}}
 if(phase==='error')return <View style={styles.screen}><Stack.Screen options={{headerShown:false}}/><ErrorState message="Couldn't load channel history." onRetry={()=>{setPhase('loading');load()}}/></View>;
 return <View style={styles.screen}><Stack.Screen options={{headerShown:false}}/><View style={styles.header}><Pressable onPress={()=>router.back()} hitSlop={10}><Ionicons name="chevron-back" size={26} color={colors.accent}/></Pressable><View><Text style={styles.title}>#{channel?.name??'channel'}</Text><Text style={styles.subtitle}>{channel?.topic||'Read-only relay'}</Text></View></View><FlatList ref={list} data={messages} keyExtractor={(m)=>m.id} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false)}}/>} ListHeaderComponent={hasMore?<Pressable style={styles.history} onPress={history}><Text style={styles.historyText}>Load older messages</Text></Pressable>:null} renderItem={({item})=><View style={styles.message}><View style={styles.avatar}><Text style={styles.avatarText}>{(item.senderName||'?').slice(0,1).toUpperCase()}</Text></View><View style={styles.body}><View style={styles.metaRow}><Text style={styles.sender}>{item.senderName||'Unknown'}</Text><Text style={styles.time}>{new Date(item.createdAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</Text></View><Text style={styles.text}>{item.text||'Attachment'}</Text></View></View>} ListEmptyComponent={<Text style={styles.empty}>No messages in this channel.</Text>}/><View style={styles.readOnly}><Ionicons name="eye-outline" size={17} color={colors.textMuted}/><Text style={styles.readOnlyText}>Server Relay is read only</Text></View></View>
}
function makeStyles(c){return StyleSheet.create({screen:{flex:1,backgroundColor:c.bg},header:{flexDirection:'row',alignItems:'center',gap:space.sm,paddingHorizontal:space.md,paddingTop:space.lg,paddingBottom:space.md,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:c.border},title:{...type.h1,color:c.textPrimary},subtitle:{...type.small,color:c.textMuted},list:{padding:space.lg,gap:space.md,flexGrow:1},message:{flexDirection:'row',gap:space.sm},avatar:{width:32,height:32,borderRadius:16,backgroundColor:c.surfaceRaised,alignItems:'center',justifyContent:'center'},avatarText:{color:c.textPrimary,fontWeight:'700'},body:{flex:1,backgroundColor:c.surface,padding:space.md,borderRadius:radius.lg},metaRow:{flexDirection:'row',gap:space.sm,alignItems:'center'},sender:{...type.small,color:c.accent,fontWeight:'700'},time:{...type.small,color:c.textMuted},text:{...type.body,color:c.textPrimary,marginTop:3},history:{alignSelf:'center',padding:space.sm},historyText:{...type.small,color:c.accent},empty:{...type.body,color:c.textMuted,textAlign:'center',marginTop:space.xl},readOnly:{flexDirection:'row',justifyContent:'center',alignItems:'center',gap:space.xs,padding:space.md,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:c.border},readOnlyText:{...type.small,color:c.textMuted}})}
